cp "./compiled/Form 6 - 000 - Cover.zip" "./annual/Form 6 - 000 - Cover.zip"
cp "./compiled/Form 6 - 000 - Instructions.zip" "./annual/Form 6 - 000 - Instructions.zip"
cp "./compiled/Form 6 - 001 - Identification.zip" "./annual/Form 6 - 001 - Identification.zip"
cp "./compiled/Form 6 - 002 - List of Schedules.zip" "./annual/Form 6 - 002 - List of Schedules.zip"
cp "./compiled/Form 6 - 101 - General Information.zip" "./annual/Form 6 - 101 - General Information.zip"
cp "./compiled/Form 6 - 102 - Control Over Respondent.zip" "./annual/Form 6 - 102 - Control Over Respondent.zip"
cp "./compiled/Form 6 - 103 - Companies Controlled by Respondent.zip" "./annual/Form 6 - 103 - Companies Controlled by Respondent.zip"
cp "./compiled/Form 6 - 104 - Officers.zip" "./annual/Form 6 - 104 - Officers.zip"
cp "./compiled/Form 6 - 105 - Directors.zip" "./annual/Form 6 - 105 - Directors.zip"
cp "./compiled/Form 6 - 108 - Important Changes During QuarterYear.zip" "./annual/Form 6 - 108 - Important Changes During QuarterYear.zip"
cp "./compiled/Form 6 - 110 - Comparative Balance Sheet.zip" "./annual/Form 6 - 110 - Comparative Balance Sheet.zip"
cp "./compiled/Form 6 - 114 - Income Statement.zip" "./annual/Form 6 - 114 - Income Statement.zip"
cp "./compiled/Form 6 - 116 - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip" "./annual/Form 6 - 116 - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip"
cp "./compiled/Form 6 - 118 - Appropriated Retained Income.zip" "./annual/Form 6 - 118 - Appropriated Retained Income.zip"
cp "./compiled/Form 6 - 119 - Unappropriated Retained Income Statement.zip" "./annual/Form 6 - 119 - Unappropriated Retained Income Statement.zip"
cp "./compiled/Form 6 - 120 - Statement of Cash Flows.zip" "./annual/Form 6 - 120 - Statement of Cash Flows.zip"
cp "./compiled/Form 6 - 122 - Notes to Financial Statements.zip" "./annual/Form 6 - 122 - Notes to Financial Statements.zip"
cp "./compiled/Form 6 - 200 - Receivables from Affiliated Companies.zip" "./annual/Form 6 - 200 - Receivables from Affiliated Companies.zip"
cp "./compiled/Form 6 - 202 - Investments in Affiliated Companies.zip" "./annual/Form 6 - 202 - Investments in Affiliated Companies.zip"
cp "./compiled/Form 6 - 204 - Invest in Com Stock of Affiliated.zip" "./annual/Form 6 - 204 - Invest in Com Stock of Affiliated.zip"
cp "./compiled/Form 6 - 212- Carrier Property.zip" "./annual/Form 6 - 212- Carrier Property.zip"
cp "./compiled/Form 6 - 214- Undivided Joint Interest Property.zip" "./annual/Form 6 - 214- Undivided Joint Interest Property.zip"
cp "./compiled/Form 6 - 216- Accrued Depreciation - Carrier Property.zip" "./annual/Form 6 - 216- Accrued Depreciation - Carrier Property.zip"
cp "./compiled/Form 6 - 217 - Accrued Depreciation - Undivided Joint Interest Property.zip" "./annual/Form 6 - 217 - Accrued Depreciation - Undivided Joint Interest Property.zip"
cp "./compiled/Form 6 - 218 - Amortization Base and Reserve.zip" "./annual/Form 6 - 218 - Amortization Base and Reserve.zip"
cp "./compiled/Form 6 - 220 - Noncarrier Property.zip" "./annual/Form 6 - 220 - Noncarrier Property.zip"
cp "./compiled/Form 6 - 221 - Other Deferred Charges.zip" "./annual/Form 6 - 221 - Other Deferred Charges.zip"
cp "./compiled/Form 6 - 225 - Payables to Affiliated Companies.zip" "./annual/Form 6 - 225 - Payables to Affiliated Companies.zip"
cp "./compiled/Form 6 - 226 - Long-Term Debt.zip" "./annual/Form 6 - 226 - Long-Term Debt.zip"
cp "./compiled/Form 6 - 230 - Analysis of Federal Income and Other Taxes Deferred.zip" "./annual/Form 6 - 230 - Analysis of Federal Income and Other Taxes Deferred.zip"
cp "./compiled/Form 6 - 250 - Capital Stock.zip" "./annual/Form 6 - 250 - Capital Stock.zip"
cp "./compiled/Form 6 - 252 - Capital Stock Changes.zip" "./annual/Form 6 - 252 - Capital Stock Changes.zip"
cp "./compiled/Form 6 - 254 - Additional Paid in Capital.zip" "./annual/Form 6 - 254 - Additional Paid in Capital.zip"
cp "./compiled/Form 6 - 300 - Operating Revenues.zip" "./annual/Form 6 - 300 - Operating Revenues.zip"
cp "./compiled/Form 6 - 301 - Operating Revenue Accounts.zip" "./annual/Form 6 - 301 - Operating Revenue Accounts.zip"
cp "./compiled/Form 6 - 302 - Operating Expense Accounts.zip" "./annual/Form 6 - 302 - Operating Expense Accounts.zip"
cp "./compiled/Form 6 - 305 - Pipeline Taxes.zip" "./annual/Form 6 - 305 - Pipeline Taxes.zip"
cp "./compiled/Form 6 - 335 - Income from Noncarrier Property.zip" "./annual/Form 6 - 335 - Income from Noncarrier Property.zip"
cp "./compiled/Form 6 - 336 - Interest and Dividend Income.zip" "./annual/Form 6 - 336 - Interest and Dividend Income.zip"
cp "./compiled/Form 6 - 337 - Miscellaneous Items in Income and Retained Income Accounts for the Year.zip" "./annual/Form 6 - 337 - Miscellaneous Items in Income and Retained Income Accounts for the Year.zip"
cp "./compiled/Form 6 - 351 - Payments for Services Rendered by Other than Employees.zip" "./annual/Form 6 - 351 - Payments for Services Rendered by Other than Employees.zip"
cp "./compiled/Form 6 - 600 - Statistics of Operations.zip" "./annual/Form 6 - 600 - Statistics of Operations.zip"
cp "./compiled/Form 6 - 600a - Statistics of Operations.zip" "./annual/Form 6 - 600a - Statistics of Operations.zip"
cp "./compiled/Form 6 - 602 - Miles of Pipeline Operated at end of Year.zip" "./annual/Form 6 - 602 - Miles of Pipeline Operated at end of Year.zip"
cp "./compiled/Form 6 - 700 - Annual Cost of Service Based Analysis Schedule.zip" "./annual/Form 6 - 700 - Annual Cost of Service Based Analysis Schedule.zip"