cp "./compiled/Form 6 - 000 - Cover.zip" "./quarterly/Form 6 - 000 - Cover.zip"
cp "./compiled/Form 6 - 000 - Instructions.zip" "./quarterly/Form 6 - 000 - Instructions.zip"
cp "./compiled/Form 6 - 001 - Identification.zip" "./quarterly/Form 6 - 001 - Identification.zip"
cp "./compiled/Form 6 - 002 - 6Q - List of Schedules.zip" "./quarterly/Form 6 - 002 - 6Q - List of Schedules.zip"
cp "./compiled/Form 6 - 108 - Important Changes During QuarterYear.zip" "./quarterly/Form 6 - 108 - Important Changes During QuarterYear.zip"
cp "./compiled/Form 6 - 110 - Comparative Balance Sheet.zip" "./quarterly/Form 6 - 110 - Comparative Balance Sheet.zip"
cp "./compiled/Form 6 - 114 - Income Statement.zip" "./quarterly/Form 6 - 114 - Income Statement.zip"
cp "./compiled/Form 6 - 116 - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip" "./quarterly/Form 6 - 116 - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip"
cp "./compiled/Form 6 - 119 - Unappropriated Retained Income Statement.zip" "./quarterly/Form 6 - 119 - Unappropriated Retained Income Statement.zip"
cp "./compiled/Form 6 - 120 - Statement of Cash Flows.zip" "./quarterly/Form 6 - 120 - Statement of Cash Flows.zip"
cp "./compiled/Form 6 - 122 - Notes to Financial Statements.zip" "./quarterly/Form 6 - 122 - Notes to Financial Statements.zip"
cp "./compiled/Form 6 - 300 - Operating Revenues.zip" "./quarterly/Form 6 - 300 - Operating Revenues.zip"
cp "./compiled/Form 6 - 302 - Operating Expense Accounts.zip" "./quarterly/Form 6 - 302 - Operating Expense Accounts.zip"
cp "./compiled/Form 6 - 600 - Statistics of Operations.zip" "./quarterly/Form 6 - 600 - Statistics of Operations.zip"
cp "./compiled/Form 6 - 600a - Statistics of Operations.zip" "./quarterly/Form 6 - 600a - Statistics of Operations.zip"