cp "./compiled/Form 1 - 000 - Cover.zip" "./quarterly/Form 1 - 000 - Cover.zip"
cp "./compiled/Form 1 - 000 - Instructions.zip" "./quarterly/Form 1 - 000 - Instructions.zip"
cp "./compiled/Form 1 - 001 - 3Q - Identification.zip" "./quarterly/Form 1 - 001 - 3Q - Identification.zip"
cp "./compiled/Form 1 - 002 - 3Q - List of Schedules.zip" "./quarterly/Form 1 - 002 - 3Q - List of Schedules.zip"
cp "./compiled/Form 1 - 108 - Important Changes.zip" "./quarterly/Form 1 - 108 - Important Changes.zip"
cp "./compiled/Form 1 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip" "./quarterly/Form 1 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip"
cp "./compiled/Form 1 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip" "./quarterly/Form 1 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip"
cp "./compiled/Form 1 - 114 - Statement of Income.zip" "./quarterly/Form 1 - 114 - Statement of Income.zip"
cp "./compiled/Form 1 - 118 - Statement of Retained Earnings.zip" "./quarterly/Form 1 - 118 - Statement of Retained Earnings.zip"
cp "./compiled/Form 1 - 120 - Statement of Cash Flows.zip" "./quarterly/Form 1 - 120 - Statement of Cash Flows.zip"
cp "./compiled/Form 1 - 122 - Notes to Financials.zip" "./quarterly/Form 1 - 122 - Notes to Financials.zip"
cp "./compiled/Form 1 - 122a - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip" "./quarterly/Form 1 - 122a - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip"
cp "./compiled/Form 1 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip" "./quarterly/Form 1 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip"
cp "./compiled/Form 1 - 208 - 3Q - ELECTRIC PLANT IN SERVICE AND ACCUMULATED PROVISION FOR DEPRECIATION BY FUNCTION.zip" "./quarterly/Form 1 - 208 - 3Q - ELECTRIC PLANT IN SERVICE AND ACCUMULATED PROVISION FOR DEPRECIATION BY FUNCTION.zip"
cp "./compiled/Form 1 - 231 - Transmission Service and Generation Interconnection Study Cost.zip" "./quarterly/Form 1 - 231 - Transmission Service and Generation Interconnection Study Cost.zip"
cp "./compiled/Form 1 - 232 - Other Regulatory Assets.zip" "./quarterly/Form 1 - 232 - Other Regulatory Assets.zip"
cp "./compiled/Form 1 - 278 - Other Regulatory Liabilities (Account 254).zip" "./quarterly/Form 1 - 278 - Other Regulatory Liabilities (Account 254).zip"
cp "./compiled/Form 1 - 300 - Electric Operating Revenues.zip" "./quarterly/Form 1 - 300 - Electric Operating Revenues.zip"
cp "./compiled/Form 1 - 302 - Regional Transmission Service Revenues.zip" "./quarterly/Form 1 - 302 - Regional Transmission Service Revenues.zip"
cp "./compiled/Form 1 - 324 - 3Q - Electric Production, Other Expenses.zip" "./quarterly/Form 1 - 324 - 3Q - Electric Production, Other Expenses.zip"
cp "./compiled/Form 1 - 325 - 3Q - Electric Customer Accounts, Service, Sales, Administrative and General Expense.zip" "./quarterly/Form 1 - 325 - 3Q - Electric Customer Accounts, Service, Sales, Administrative and General Expense.zip"
cp "./compiled/Form 1 - 328 - Transmission of Electricity for Others.zip" "./quarterly/Form 1 - 328 - Transmission of Electricity for Others.zip"
cp "./compiled/Form 1 - 331 - Transmission of Electricity by ISO RTOs.zip" "./quarterly/Form 1 - 331 - Transmission of Electricity by ISO RTOs.zip"
cp "./compiled/Form 1 - 332 - Transmission of Electricity by Others.zip" "./quarterly/Form 1 - 332 - Transmission of Electricity by Others.zip"
cp "./compiled/Form 1 - 338 - 3Q - Depreciation, Depletion and Amortization of Electric Plant.zip" "./quarterly/Form 1 - 338 - 3Q - Depreciation, Depletion and Amortization of Electric Plant.zip"
cp "./compiled/Form 1 - 397 - Amounts Included in ISO RTO Settlement Statements.zip" "./quarterly/Form 1 - 397 - Amounts Included in ISO RTO Settlement Statements.zip"
cp "./compiled/Form 1 - 399 - 3Q - Monthly Peaks and Output.zip" "./quarterly/Form 1 - 399 - 3Q - Monthly Peaks and Output.zip"
cp "./compiled/Form 1 - 400 - Monthly Trans Peak Load.zip" "./quarterly/Form 1 - 400 - Monthly Trans Peak Load.zip"
cp "./compiled/Form 1 - 400a - ISO-RTO Monthly Trans Peak Load.zip" "./quarterly/Form 1 - 400a - ISO-RTO Monthly Trans Peak Load.zip"