cp "./compiled/Form 2 - 000 - Cover.zip" "./quarterly/Form 2 - 000 - Cover.zip"
cp "./compiled/Form 2 - 000 - Instructions.zip" "./quarterly/Form 2 - 000 - Instructions.zip"
cp "./compiled/Form 2 - 001 - Identification.zip" "./quarterly/Form 2 - 001 - Identification.zip"
cp "./compiled/Form 2 - 002 - 2Q - List of Schedules (Natural Gas Company).zip" "./quarterly/Form 2 - 002 - 2Q - List of Schedules (Natural Gas Company).zip"
cp "./compiled/Form 2 - 108 - Important Changes During QuarterYear.zip" "./quarterly/Form 2 - 108 - Important Changes During QuarterYear.zip"
cp "./compiled/Form 2 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip" "./quarterly/Form 2 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip"
cp "./compiled/Form 2 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip" "./quarterly/Form 2 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip"
cp "./compiled/Form 2 - 114 - Statement of Income.zip" "./quarterly/Form 2 - 114 - Statement of Income.zip"
cp "./compiled/Form 2 - 117 - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip" "./quarterly/Form 2 - 117 - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip"
cp "./compiled/Form 2 - 118 - Statement of Retained Earnings.zip" "./quarterly/Form 2 - 118 - Statement of Retained Earnings.zip"
cp "./compiled/Form 2 - 120 - Statement of Cash Flows.zip" "./quarterly/Form 2 - 120 - Statement of Cash Flows.zip"
cp "./compiled/Form 2 - 122 - Notes to Financial Statements.zip" "./quarterly/Form 2 - 122 - Notes to Financial Statements.zip"
cp "./compiled/Form 2 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip" "./quarterly/Form 2 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip"
cp "./compiled/Form 2 - 210 - 2Q - Gas Plant in Service and Accumulated Provision for Depreciation by Function.zip" "./quarterly/Form 2 - 210 - 2Q - Gas Plant in Service and Accumulated Provision for Depreciation by Function.zip"
cp "./compiled/Form 2 - 232 - Other Regulatory Assets.zip" "./quarterly/Form 2 - 232 - Other Regulatory Assets.zip"
cp "./compiled/Form 2 - 278 - Other Regulatory Liabilities (Account 254).zip" "./quarterly/Form 2 - 278 - Other Regulatory Liabilities (Account 254).zip"
cp "./compiled/Form 2 - 299 - Monthly Quantity _ Revenue Data by Rate Schedule.zip" "./quarterly/Form 2 - 299 - Monthly Quantity _ Revenue Data by Rate Schedule.zip"
cp "./compiled/Form 2 - 309 - 2Q - Natural Gas Company- Gas Revenues and Dekatherms.zip" "./quarterly/Form 2 - 309 - 2Q - Natural Gas Company- Gas Revenues and Dekatherms.zip"
cp "./compiled/Form 2 - 310 - 2Q - Gas Production and Other Gas Supply Expense.zip" "./quarterly/Form 2 - 310 - 2Q - Gas Production and Other Gas Supply Expense.zip"
cp "./compiled/Form 2 - 311 - 2Q - Natural Gas Storage, Terminaling, Processing Services.zip" "./quarterly/Form 2 - 311 - 2Q - Natural Gas Storage, Terminaling, Processing Services.zip"
cp "./compiled/Form 2 - 312 - 2Q - Gas Customer Accounts, Service, Sales, Administrative and General Expenses.zip" "./quarterly/Form 2 - 312 - 2Q - Gas Customer Accounts, Service, Sales, Administrative and General Expenses.zip"
cp "./compiled/Form 2 - 339 - 2Q - Depreciation, Depletion and Amortization of Gas Plant.zip" "./quarterly/Form 2 - 339 - 2Q - Depreciation, Depletion and Amortization of Gas Plant.zip"
cp "./compiled/Form 2 - 520 - Gas Account - Natural Gas.zip" "./quarterly/Form 2 - 520 - Gas Account - Natural Gas.zip"
cp "./compiled/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M1.zip" "./quarterly/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M1.zip"
cp "./compiled/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M2.zip" "./quarterly/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M2.zip"
cp "./compiled/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M3.zip" "./quarterly/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M3.zip"