cp "./compiled/Form 1 - 000 - Cover.zip" "./annual/Form 1 - 000 - Cover.zip"
cp "./compiled/Form 1 - 000 - Instructions.zip" "./annual/Form 1 - 000 - Instructions.zip"
cp "./compiled/Form 1 - 001 - Identification.zip" "./annual/Form 1 - 001 - Identification.zip"
cp "./compiled/Form 1 - 002 - List of Schedules.zip" "./annual/Form 1 - 002 - List of Schedules.zip"
cp "./compiled/Form 1 - 101 - General Information.zip" "./annual/Form 1 - 101 - General Information.zip"
cp "./compiled/Form 1 - 102 - Control Over Respondent.zip" "./annual/Form 1 - 102 - Control Over Respondent.zip"
cp "./compiled/Form 1 - 103 - Corporations Controlled by Respondent.zip" "./annual/Form 1 - 103 - Corporations Controlled by Respondent.zip"
cp "./compiled/Form 1 - 104 - Officers.zip" "./annual/Form 1 - 104 - Officers.zip"
cp "./compiled/Form 1 - 105 - Directors.zip" "./annual/Form 1 - 105 - Directors.zip"
cp "./compiled/Form 1 - 106 - Information on Formula Rates.zip" "./annual/Form 1 - 106 - Information on Formula Rates.zip"
cp "./compiled/Form 1 - 106a - Information on Formula Rates.zip" "./annual/Form 1 - 106a - Information on Formula Rates.zip"
cp "./compiled/Form 1 - 106b - Information on Formula Rates.zip" "./annual/Form 1 - 106b - Information on Formula Rates.zip"
cp "./compiled/Form 1 - 108 - Important Changes.zip" "./annual/Form 1 - 108 - Important Changes.zip"
cp "./compiled/Form 1 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip" "./annual/Form 1 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip"
cp "./compiled/Form 1 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip" "./annual/Form 1 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip"
cp "./compiled/Form 1 - 114 - Statement of Income.zip" "./annual/Form 1 - 114 - Statement of Income.zip"
cp "./compiled/Form 1 - 118 - Statement of Retained Earnings.zip" "./annual/Form 1 - 118 - Statement of Retained Earnings.zip"
cp "./compiled/Form 1 - 120 - Statement of Cash Flows.zip" "./annual/Form 1 - 120 - Statement of Cash Flows.zip"
cp "./compiled/Form 1 - 122 - Notes to Financials.zip" "./annual/Form 1 - 122 - Notes to Financials.zip"
cp "./compiled/Form 1 - 122a - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip" "./annual/Form 1 - 122a - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip"
cp "./compiled/Form 1 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip" "./annual/Form 1 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip"
cp "./compiled/Form 1 - 202 - Nuclear Fuel.zip" "./annual/Form 1 - 202 - Nuclear Fuel.zip"
cp "./compiled/Form 1 - 204 - Electric Plant in Service.zip" "./annual/Form 1 - 204 - Electric Plant in Service.zip"
cp "./compiled/Form 1 - 213 - Electric Plant Leased to Others.zip" "./annual/Form 1 - 213 - Electric Plant Leased to Others.zip"
cp "./compiled/Form 1 - 214 - Electric Plant Held for Future Use.zip" "./annual/Form 1 - 214 - Electric Plant Held for Future Use.zip"
cp "./compiled/Form 1 - 216 - Construction Work in Progress - Electric.zip" "./annual/Form 1 - 216 - Construction Work in Progress - Electric.zip"
cp "./compiled/Form 1 - 219 - Accumulated Provision for Depreciation of Electric Utility Plant.zip" "./annual/Form 1 - 219 - Accumulated Provision for Depreciation of Electric Utility Plant.zip"
cp "./compiled/Form 1 - 224 - Investments in Subsidiary Companies.zip" "./annual/Form 1 - 224 - Investments in Subsidiary Companies.zip"
cp "./compiled/Form 1 - 227 - Materials and Supplies.zip" "./annual/Form 1 - 227 - Materials and Supplies.zip"
cp "./compiled/Form 1 - 228a - Allowances (Accounts 158.1 and 158.2).zip" "./annual/Form 1 - 228a - Allowances (Accounts 158.1 and 158.2).zip"
cp "./compiled/Form 1 - 228b - Allowances (Accounts 158.1 and 158.2).zip" "./annual/Form 1 - 228b - Allowances (Accounts 158.1 and 158.2).zip"
cp "./compiled/Form 1 - 230a - Extraordinary Property Losses.zip" "./annual/Form 1 - 230a - Extraordinary Property Losses.zip"
cp "./compiled/Form 1 - 230b - Unrecovered Plant and Regulatory Study Costs.zip" "./annual/Form 1 - 230b - Unrecovered Plant and Regulatory Study Costs.zip"
cp "./compiled/Form 1 - 231 - Transmission Service and Generation Interconnection Study Cost.zip" "./annual/Form 1 - 231 - Transmission Service and Generation Interconnection Study Cost.zip"
cp "./compiled/Form 1 - 232 - Other Regulatory Assets.zip" "./annual/Form 1 - 232 - Other Regulatory Assets.zip"
cp "./compiled/Form 1 - 233 - Miscellaneous Deferred Debits (Account 186).zip" "./annual/Form 1 - 233 - Miscellaneous Deferred Debits (Account 186).zip"
cp "./compiled/Form 1 - 234 - Accumulated Deferred Income Taxes.zip" "./annual/Form 1 - 234 - Accumulated Deferred Income Taxes.zip"
cp "./compiled/Form 1 - 250 - Capital Stock.zip" "./annual/Form 1 - 250 - Capital Stock.zip"
cp "./compiled/Form 1 - 253 - Other Paid-In Capital (Accounts 208-211).zip" "./annual/Form 1 - 253 - Other Paid-In Capital (Accounts 208-211).zip"
cp "./compiled/Form 1 - 254b - Capital Stock Expense (Account 214).zip" "./annual/Form 1 - 254b - Capital Stock Expense (Account 214).zip"
cp "./compiled/Form 1 - 256 - Long-Term Debt.zip" "./annual/Form 1 - 256 - Long-Term Debt.zip"
cp "./compiled/Form 1 - 261 - Reconciliation of Reported Net Income with Taxable Income for Federal Income Taxes.zip" "./annual/Form 1 - 261 - Reconciliation of Reported Net Income with Taxable Income for Federal Income Taxes.zip"
cp "./compiled/Form 1 - 262 - Taxes Accrued, Prepaid and Charged During Year.zip" "./annual/Form 1 - 262 - Taxes Accrued, Prepaid and Charged During Year.zip"
cp "./compiled/Form 1 - 266 - Accumulated Deferred Income Tax Credits.zip" "./annual/Form 1 - 266 - Accumulated Deferred Income Tax Credits.zip"
cp "./compiled/Form 1 - 269 - Other Deferred Credits (Account 253).zip" "./annual/Form 1 - 269 - Other Deferred Credits (Account 253).zip"
cp "./compiled/Form 1 - 272 - Accumulated Deferred Income Taxes-Accelerated Amortization Property.zip" "./annual/Form 1 - 272 - Accumulated Deferred Income Taxes-Accelerated Amortization Property.zip"
cp "./compiled/Form 1 - 274 - Accumulated Deferred Income Taxes - Other Property (Account 282).zip" "./annual/Form 1 - 274 - Accumulated Deferred Income Taxes - Other Property (Account 282).zip"
cp "./compiled/Form 1 - 276 - ADIT-Other.zip" "./annual/Form 1 - 276 - ADIT-Other.zip"
cp "./compiled/Form 1 - 278 - Other Regulatory Liabilities (Account 254).zip" "./annual/Form 1 - 278 - Other Regulatory Liabilities (Account 254).zip"
cp "./compiled/Form 1 - 300 - Electric Operating Revenues.zip" "./annual/Form 1 - 300 - Electric Operating Revenues.zip"
cp "./compiled/Form 1 - 302 - Regional Transmission Service Revenues.zip" "./annual/Form 1 - 302 - Regional Transmission Service Revenues.zip"
cp "./compiled/Form 1 - 304 - Sales of Electricity by Rate Schedules 440.zip" "./annual/Form 1 - 304 - Sales of Electricity by Rate Schedules 440.zip"
cp "./compiled/Form 1 - 304 - Sales of Electricity by Rate Schedules 442 - Commercial.zip" "./annual/Form 1 - 304 - Sales of Electricity by Rate Schedules 442 - Commercial.zip"
cp "./compiled/Form 1 - 304 - Sales of Electricity by Rate Schedules 442 - Industrial.zip" "./annual/Form 1 - 304 - Sales of Electricity by Rate Schedules 442 - Industrial.zip"
cp "./compiled/Form 1 - 304 - Sales of Electricity by Rate Schedules 442.zip" "./annual/Form 1 - 304 - Sales of Electricity by Rate Schedules 442.zip"
cp "./compiled/Form 1 - 304 - Sales of Electricity by Rate Schedules 444.zip" "./annual/Form 1 - 304 - Sales of Electricity by Rate Schedules 444.zip"
cp "./compiled/Form 1 - 304 - Sales of Electricity by Rate Schedules 445.zip" "./annual/Form 1 - 304 - Sales of Electricity by Rate Schedules 445.zip"
cp "./compiled/Form 1 - 304 - Sales of Electricity by Rate Schedules 446.zip" "./annual/Form 1 - 304 - Sales of Electricity by Rate Schedules 446.zip"
cp "./compiled/Form 1 - 304 - Sales of Electricity by Rate Schedules 448.zip" "./annual/Form 1 - 304 - Sales of Electricity by Rate Schedules 448.zip"
cp "./compiled/Form 1 - 304 - Sales of Electricity by Rate Schedules 449.zip" "./annual/Form 1 - 304 - Sales of Electricity by Rate Schedules 449.zip"
cp "./compiled/Form 1 - 304 - Sales of Electricity by Rate Schedules.zip" "./annual/Form 1 - 304 - Sales of Electricity by Rate Schedules.zip"
cp "./compiled/Form 1 - 310 - Sales for Resale.zip" "./annual/Form 1 - 310 - Sales for Resale.zip"
cp "./compiled/Form 1 - 320 - Electric Operations And Maintenance Expenses.zip" "./annual/Form 1 - 320 - Electric Operations And Maintenance Expenses.zip"
cp "./compiled/Form 1 - 326 - Purchased Power.zip" "./annual/Form 1 - 326 - Purchased Power.zip"
cp "./compiled/Form 1 - 328 - Transmission of Electricity for Others.zip" "./annual/Form 1 - 328 - Transmission of Electricity for Others.zip"
cp "./compiled/Form 1 - 331 - Transmission of Electricity by ISO RTOs.zip" "./annual/Form 1 - 331 - Transmission of Electricity by ISO RTOs.zip"
cp "./compiled/Form 1 - 332 - Transmission of Electricity by Others.zip" "./annual/Form 1 - 332 - Transmission of Electricity by Others.zip"
cp "./compiled/Form 1 - 335 - Miscellaneous General Expenses.zip" "./annual/Form 1 - 335 - Miscellaneous General Expenses.zip"
cp "./compiled/Form 1 - 336 - Depreciation and Amortization of Electric Plant.zip" "./annual/Form 1 - 336 - Depreciation and Amortization of Electric Plant.zip"
cp "./compiled/Form 1 - 350 - Regulatory Commission Expenses.zip" "./annual/Form 1 - 350 - Regulatory Commission Expenses.zip"
cp "./compiled/Form 1 - 352 - Research, Development and Demonstration Activities.zip" "./annual/Form 1 - 352 - Research, Development and Demonstration Activities.zip"
cp "./compiled/Form 1 - 354 - Distribution of Salaries and Wages.zip" "./annual/Form 1 - 354 - Distribution of Salaries and Wages.zip"
cp "./compiled/Form 1 - 356 - Common Utility Plant and Expenses.zip" "./annual/Form 1 - 356 - Common Utility Plant and Expenses.zip"
cp "./compiled/Form 1 - 397 - Amounts Included in ISO RTO Settlement Statements.zip" "./annual/Form 1 - 397 - Amounts Included in ISO RTO Settlement Statements.zip"
cp "./compiled/Form 1 - 398 - Purchases and Sales of Ancillary Services.zip" "./annual/Form 1 - 398 - Purchases and Sales of Ancillary Services.zip"
cp "./compiled/Form 1 - 400 - Monthly Trans Peak Load.zip" "./annual/Form 1 - 400 - Monthly Trans Peak Load.zip"
cp "./compiled/Form 1 - 400a - ISO-RTO Monthly Trans Peak Load.zip" "./annual/Form 1 - 400a - ISO-RTO Monthly Trans Peak Load.zip"
cp "./compiled/Form 1 - 401a - Electric Energy Account.zip" "./annual/Form 1 - 401a - Electric Energy Account.zip"
cp "./compiled/Form 1 - 401b - Monthly Peaks and Output.zip" "./annual/Form 1 - 401b - Monthly Peaks and Output.zip"
cp "./compiled/Form 1 - 402 - Steam Electric Generating Plant Statistics.zip" "./annual/Form 1 - 402 - Steam Electric Generating Plant Statistics.zip"
cp "./compiled/Form 1 - 406 - Hydroelectric Generating Plant Statistics.zip" "./annual/Form 1 - 406 - Hydroelectric Generating Plant Statistics.zip"
cp "./compiled/Form 1 - 408 - Pumped Storage Generating Plant Statistics.zip" "./annual/Form 1 - 408 - Pumped Storage Generating Plant Statistics.zip"
cp "./compiled/Form 1 - 410 - Generating Plant Statistics.zip" "./annual/Form 1 - 410 - Generating Plant Statistics.zip"
cp "./compiled/Form 1 - 414 - ENERGY STORAGE OPERATIONS.zip" "./annual/Form 1 - 414 - ENERGY STORAGE OPERATIONS.zip"
cp "./compiled/Form 1 - 422 - Transmission Line Statistics.zip" "./annual/Form 1 - 422 - Transmission Line Statistics.zip"
cp "./compiled/Form 1 - 424 - Transmission Lines Added During Year.zip" "./annual/Form 1 - 424 - Transmission Lines Added During Year.zip"
cp "./compiled/Form 1 - 426 - Substations.zip" "./annual/Form 1 - 426 - Substations.zip"
cp "./compiled/Form 1 - 429 - Transactions With Associated Affiliated Companies.zip" "./annual/Form 1 - 429 - Transactions With Associated Affiliated Companies.zip"