cp "./compiled/Form 2 - 000 - 2A - Cover.zip" "./form2A/Form 2 - 000 - 2A - Cover.zip"
cp "./compiled/Form 2 - 000 - Instructions.zip" "./form2A/Form 2 - 000 - Instructions.zip"
cp "./compiled/Form 2 - 001 - 2A - Identification.zip" "./form2A/Form 2 - 001 - 2A - Identification.zip"
cp "./compiled/Form 2 - 002 - 2A - List of Schedules (Natural Gas Company).zip" "./form2A/Form 2 - 002 - 2A - List of Schedules (Natural Gas Company).zip"
cp "./compiled/Form 2 - 107 - Security Holders and Voting Powers.zip" "./form2A/Form 2 - 107 - Security Holders and Voting Powers.zip"
cp "./compiled/Form 2 - 108 - Important Changes During QuarterYear.zip" "./form2A/Form 2 - 108 - Important Changes During QuarterYear.zip"
cp "./compiled/Form 2 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip" "./form2A/Form 2 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip"
cp "./compiled/Form 2 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip" "./form2A/Form 2 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip"
cp "./compiled/Form 2 - 114 - Statement of Income.zip" "./form2A/Form 2 - 114 - Statement of Income.zip"
cp "./compiled/Form 2 - 117 - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip" "./form2A/Form 2 - 117 - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip"
cp "./compiled/Form 2 - 118 - Statement of Retained Earnings.zip" "./form2A/Form 2 - 118 - Statement of Retained Earnings.zip"
cp "./compiled/Form 2 - 120 - Statement of Cash Flows.zip" "./form2A/Form 2 - 120 - Statement of Cash Flows.zip"
cp "./compiled/Form 2 - 122 - Notes to Financial Statements.zip" "./form2A/Form 2 - 122 - Notes to Financial Statements.zip"
cp "./compiled/Form 2 - 204 - Gas Plant in Service (Accounts 101, 102, 103, and 106).zip" "./form2A/Form 2 - 204 - Gas Plant in Service (Accounts 101, 102, 103, and 106).zip"
cp "./compiled/Form 2 - 211.1 - 2A - General Information on Plant and Operations.zip" "./form2A/Form 2 - 211.1 - 2A - General Information on Plant and Operations.zip"
cp "./compiled/Form 2 - 212 - Gas Property and Capacity Leased from Others.zip" "./form2A/Form 2 - 212 - Gas Property and Capacity Leased from Others.zip"
cp "./compiled/Form 2 - 213 - Gas Property and Capacity Leased to Others.zip" "./form2A/Form 2 - 213 - Gas Property and Capacity Leased to Others.zip"
cp "./compiled/Form 2 - 217 - Non-Traditional Rate Treatment Afforded New Projects.zip" "./form2A/Form 2 - 217 - Non-Traditional Rate Treatment Afforded New Projects.zip"
cp "./compiled/Form 2 - 219 - Accumulated Provision for Depreciation of Gas Utility Plant (Account 108).zip" "./form2A/Form 2 - 219 - Accumulated Provision for Depreciation of Gas Utility Plant (Account 108).zip"
cp "./compiled/Form 2 - 232 - Other Regulatory Assets.zip" "./form2A/Form 2 - 232 - Other Regulatory Assets.zip"
cp "./compiled/Form 2 - 234 - Accumulated Deferred Income Taxes (Account 190).zip" "./form2A/Form 2 - 234 - Accumulated Deferred Income Taxes (Account 190).zip"
cp "./compiled/Form 2 - 250 - 2A - Capital Stock.zip" "./form2A/Form 2 - 250 - 2A - Capital Stock.zip"
cp "./compiled/Form 2 - 262 - Taxes Accrued, Prepaid and Charged.zip" "./form2A/Form 2 - 262 - Taxes Accrued, Prepaid and Charged.zip"
cp "./compiled/Form 2 - 274 - Accumulated Deferred Income Taxes - Other Property (Account 282).zip" "./form2A/Form 2 - 274 - Accumulated Deferred Income Taxes - Other Property (Account 282).zip"
cp "./compiled/Form 2 - 276 - Accumulated Deferred Income Taxes-Other.zip" "./form2A/Form 2 - 276 - Accumulated Deferred Income Taxes-Other.zip"
cp "./compiled/Form 2 - 278 - Other Regulatory Liabilities (Account 254).zip" "./form2A/Form 2 - 278 - Other Regulatory Liabilities (Account 254).zip"
cp "./compiled/Form 2 - 300 - Gas Operating Revenues.zip" "./form2A/Form 2 - 300 - Gas Operating Revenues.zip"
cp "./compiled/Form 2 - 308 - Other Gas Revenues (Account 495).zip" "./form2A/Form 2 - 308 - Other Gas Revenues (Account 495).zip"
cp "./compiled/Form 2 - 313 - Discounted Rate Services and Negotiated Rate Services.zip" "./form2A/Form 2 - 313 - Discounted Rate Services and Negotiated Rate Services.zip"
cp "./compiled/Form 2 - 317 - Gas Operation And Maintenance Expenses.zip" "./form2A/Form 2 - 317 - Gas Operation And Maintenance Expenses.zip"
cp "./compiled/Form 2 - 352 - Employee Pensions And Benefits (Account 926).zip" "./form2A/Form 2 - 352 - Employee Pensions And Benefits (Account 926).zip"
cp "./compiled/Form 2 - 357 - Charges for Outside Professional and Other Consultative Services.zip" "./form2A/Form 2 - 357 - Charges for Outside Professional and Other Consultative Services.zip"
cp "./compiled/Form 2 - 358 - Transactions With Associated (Affiliated) Companies.zip" "./form2A/Form 2 - 358 - Transactions With Associated (Affiliated) Companies.zip"
cp "./compiled/Form 2 - 520 - Gas Account - Natural Gas.zip" "./form2A/Form 2 - 520 - Gas Account - Natural Gas.zip"
cp "./compiled/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M1.zip" "./form2A/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M1.zip"
cp "./compiled/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M2.zip" "./form2A/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M2.zip"
cp "./compiled/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M3.zip" "./form2A/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M3.zip"
cp "./compiled/Form 2 - 522.1 - System Maps.zip" "./form2A/Form 2 - 522.1 - System Maps.zip"