cp "./compiled/Form 2 - 000 - Cover.zip" "./annual/Form 2 - 000 - Cover.zip"
cp "./compiled/Form 2 - 000 - Instructions.zip" "./annual/Form 2 - 000 - Instructions.zip"
cp "./compiled/Form 2 - 001 - Identification.zip" "./annual/Form 2 - 001 - Identification.zip"
cp "./compiled/Form 2 - 002 - List of Schedules (Natural Gas Company).zip" "./annual/Form 2 - 002 - List of Schedules (Natural Gas Company).zip"
cp "./compiled/Form 2 - 101 - General Information.zip" "./annual/Form 2 - 101 - General Information.zip"
cp "./compiled/Form 2 - 102 - Control Over Respondent.zip" "./annual/Form 2 - 102 - Control Over Respondent.zip"
cp "./compiled/Form 2 - 103 - Corporations Controlled by Respondent.zip" "./annual/Form 2 - 103 - Corporations Controlled by Respondent.zip"
cp "./compiled/Form 2 - 107 - Security Holders and Voting Powers.zip" "./annual/Form 2 - 107 - Security Holders and Voting Powers.zip"
cp "./compiled/Form 2 - 108 - Important Changes During QuarterYear.zip" "./annual/Form 2 - 108 - Important Changes During QuarterYear.zip"
cp "./compiled/Form 2 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip" "./annual/Form 2 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip"
cp "./compiled/Form 2 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip" "./annual/Form 2 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip"
cp "./compiled/Form 2 - 114 - Statement of Income.zip" "./annual/Form 2 - 114 - Statement of Income.zip"
cp "./compiled/Form 2 - 117 - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip" "./annual/Form 2 - 117 - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip"
cp "./compiled/Form 2 - 118 - Statement of Retained Earnings.zip" "./annual/Form 2 - 118 - Statement of Retained Earnings.zip"
cp "./compiled/Form 2 - 120 - Statement of Cash Flows.zip" "./annual/Form 2 - 120 - Statement of Cash Flows.zip"
cp "./compiled/Form 2 - 122 - Notes to Financial Statements.zip" "./annual/Form 2 - 122 - Notes to Financial Statements.zip"
cp "./compiled/Form 2 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip" "./annual/Form 2 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip"
cp "./compiled/Form 2 - 204 - Gas Plant in Service (Accounts 101, 102, 103, and 106).zip" "./annual/Form 2 - 204 - Gas Plant in Service (Accounts 101, 102, 103, and 106).zip"
cp "./compiled/Form 2 - 212 - Gas Property and Capacity Leased from Others.zip" "./annual/Form 2 - 212 - Gas Property and Capacity Leased from Others.zip"
cp "./compiled/Form 2 - 213 - Gas Property and Capacity Leased to Others.zip" "./annual/Form 2 - 213 - Gas Property and Capacity Leased to Others.zip"
cp "./compiled/Form 2 - 214 - Gas Plant Held for Future Use (Account 105).zip" "./annual/Form 2 - 214 - Gas Plant Held for Future Use (Account 105).zip"
cp "./compiled/Form 2 - 216 - Construction Work in Progress - Gas (Account 107).zip" "./annual/Form 2 - 216 - Construction Work in Progress - Gas (Account 107).zip"
cp "./compiled/Form 2 - 217 - Non-Traditional Rate Treatment Afforded New Projects.zip" "./annual/Form 2 - 217 - Non-Traditional Rate Treatment Afforded New Projects.zip"
cp "./compiled/Form 2 - 218 - General Description of Construction Overhead procedure.zip" "./annual/Form 2 - 218 - General Description of Construction Overhead procedure.zip"
cp "./compiled/Form 2 - 219 - Accumulated Provision for Depreciation of Gas Utility Plant (Account 108).zip" "./annual/Form 2 - 219 - Accumulated Provision for Depreciation of Gas Utility Plant (Account 108).zip"
cp "./compiled/Form 2 - 220 - Gas Stored.zip" "./annual/Form 2 - 220 - Gas Stored.zip"
cp "./compiled/Form 2 - 222 - Investments.zip" "./annual/Form 2 - 222 - Investments.zip"
cp "./compiled/Form 2 - 224 - Investments in Subsidiary Companies.zip" "./annual/Form 2 - 224 - Investments in Subsidiary Companies.zip"
cp "./compiled/Form 2 - 230a - Prepayments.zip" "./annual/Form 2 - 230a - Prepayments.zip"
cp "./compiled/Form 2 - 230b - Extraordinary Property Losses (Account 182.1).zip" "./annual/Form 2 - 230b - Extraordinary Property Losses (Account 182.1).zip"
cp "./compiled/Form 2 - 230c - Unrecovered Plant and Regulatory Study Cost (Account 182.2).zip" "./annual/Form 2 - 230c - Unrecovered Plant and Regulatory Study Cost (Account 182.2).zip"
cp "./compiled/Form 2 - 232 - Other Regulatory Assets.zip" "./annual/Form 2 - 232 - Other Regulatory Assets.zip"
cp "./compiled/Form 2 - 233 - Miscellaneous Deferred Debits (Account 186).zip" "./annual/Form 2 - 233 - Miscellaneous Deferred Debits (Account 186).zip"
cp "./compiled/Form 2 - 234 - Accumulated Deferred Income Taxes (Account 190).zip" "./annual/Form 2 - 234 - Accumulated Deferred Income Taxes (Account 190).zip"
cp "./compiled/Form 2 - 250 - Capital Stock.zip" "./annual/Form 2 - 250 - Capital Stock.zip"
cp "./compiled/Form 2 - 252 - Capital Stock - Subscribed.zip" "./annual/Form 2 - 252 - Capital Stock - Subscribed.zip"
cp "./compiled/Form 2 - 253 - Other Paid-In Capital (Accounts 208-211).zip" "./annual/Form 2 - 253 - Other Paid-In Capital (Accounts 208-211).zip"
cp "./compiled/Form 2 - 254 - Discount on Capital Stock (Account 213) - Capital Stock Expense (Account 214).zip" "./annual/Form 2 - 254 - Discount on Capital Stock (Account 213) - Capital Stock Expense (Account 214).zip"
cp "./compiled/Form 2 - 255.1 - Securities Issued or Assumed and Securities Refunded or Retired.zip" "./annual/Form 2 - 255.1 - Securities Issued or Assumed and Securities Refunded or Retired.zip"
cp "./compiled/Form 2 - 256 - Long-Term Debt (Accounts 221, 222, 233 and 224).zip" "./annual/Form 2 - 256 - Long-Term Debt (Accounts 221, 222, 233 and 224).zip"
cp "./compiled/Form 2 - 258 - Unamortized Debt Expense, Premium And Discount On Long-Term Debt.zip" "./annual/Form 2 - 258 - Unamortized Debt Expense, Premium And Discount On Long-Term Debt.zip"
cp "./compiled/Form 2 - 260 - Unamortized Loss And Gain On Reacquired Debt.zip" "./annual/Form 2 - 260 - Unamortized Loss And Gain On Reacquired Debt.zip"
cp "./compiled/Form 2 - 261 - Reconciliation of Reported Net Income with Taxable Income for Federal Income Taxes.zip" "./annual/Form 2 - 261 - Reconciliation of Reported Net Income with Taxable Income for Federal Income Taxes.zip"
cp "./compiled/Form 2 - 262 - Taxes Accrued, Prepaid and Charged.zip" "./annual/Form 2 - 262 - Taxes Accrued, Prepaid and Charged.zip"
cp "./compiled/Form 2 - 268 - Miscellaneous Current and Accrued Liabilities (Account 242).zip" "./annual/Form 2 - 268 - Miscellaneous Current and Accrued Liabilities (Account 242).zip"
cp "./compiled/Form 2 - 269 - Other Deferred Credits (Account 253).zip" "./annual/Form 2 - 269 - Other Deferred Credits (Account 253).zip"
cp "./compiled/Form 2 - 274 - Accumulated Deferred Income Taxes - Other Property (Account 282).zip" "./annual/Form 2 - 274 - Accumulated Deferred Income Taxes - Other Property (Account 282).zip"
cp "./compiled/Form 2 - 276 - Accumulated Deferred Income Taxes-Other.zip" "./annual/Form 2 - 276 - Accumulated Deferred Income Taxes-Other.zip"
cp "./compiled/Form 2 - 278 - Other Regulatory Liabilities (Account 254).zip" "./annual/Form 2 - 278 - Other Regulatory Liabilities (Account 254).zip"
cp "./compiled/Form 2 - 299 - Monthly Quantity _ Revenue Data by Rate Schedule.zip" "./annual/Form 2 - 299 - Monthly Quantity _ Revenue Data by Rate Schedule.zip"
cp "./compiled/Form 2 - 300 - Gas Operating Revenues.zip" "./annual/Form 2 - 300 - Gas Operating Revenues.zip"
cp "./compiled/Form 2 - 302 - Revenues from Transportation of Gas of Others Through Gathering Facilities (Account 489.1).zip" "./annual/Form 2 - 302 - Revenues from Transportation of Gas of Others Through Gathering Facilities (Account 489.1).zip"
cp "./compiled/Form 2 - 304 - Revenues from Transportation of Gas of Others Through Transmission Facilities (Account 489.2).zip" "./annual/Form 2 - 304 - Revenues from Transportation of Gas of Others Through Transmission Facilities (Account 489.2).zip"
cp "./compiled/Form 2 - 306 - Revenues From Storing Gas Of Others.zip" "./annual/Form 2 - 306 - Revenues From Storing Gas Of Others.zip"
cp "./compiled/Form 2 - 308 - Other Gas Revenues (Account 495).zip" "./annual/Form 2 - 308 - Other Gas Revenues (Account 495).zip"
cp "./compiled/Form 2 - 313 - Discounted Rate Services and Negotiated Rate Services.zip" "./annual/Form 2 - 313 - Discounted Rate Services and Negotiated Rate Services.zip"
cp "./compiled/Form 2 - 317 - Gas Operation And Maintenance Expenses.zip" "./annual/Form 2 - 317 - Gas Operation And Maintenance Expenses.zip"
cp "./compiled/Form 2 - 328 - Exchange And Imbalance Transactions.zip" "./annual/Form 2 - 328 - Exchange And Imbalance Transactions.zip"
cp "./compiled/Form 2 - 331 - Gas Used In Utility Operations.zip" "./annual/Form 2 - 331 - Gas Used In Utility Operations.zip"
cp "./compiled/Form 2 - 332 - Transmission And Compression Of Gas By Others (Account 858).zip" "./annual/Form 2 - 332 - Transmission And Compression Of Gas By Others (Account 858).zip"
cp "./compiled/Form 2 - 334 - Other Gas Supply Expenses (Account 813).zip" "./annual/Form 2 - 334 - Other Gas Supply Expenses (Account 813).zip"
cp "./compiled/Form 2 - 335 - Miscellaneous General Expenses (Account 930.2).zip" "./annual/Form 2 - 335 - Miscellaneous General Expenses (Account 930.2).zip"
cp "./compiled/Form 2 - 336 - Depreciation, Depletion And Amortization Of Gas Plant - Section A.zip" "./annual/Form 2 - 336 - Depreciation, Depletion And Amortization Of Gas Plant - Section A.zip"
cp "./compiled/Form 2 - 336 - Depreciation, Depletion And Amortization Of Gas Plant - Section B.zip" "./annual/Form 2 - 336 - Depreciation, Depletion And Amortization Of Gas Plant - Section B.zip"
cp "./compiled/Form 2 - 340 - Particulars Concerning Certain Income Deductions And Interest Charges Accounts.zip" "./annual/Form 2 - 340 - Particulars Concerning Certain Income Deductions And Interest Charges Accounts.zip"
cp "./compiled/Form 2 - 350 - Regulatory Commission Expenses (Account 928).zip" "./annual/Form 2 - 350 - Regulatory Commission Expenses (Account 928).zip"
cp "./compiled/Form 2 - 352 - Employee Pensions And Benefits (Account 926).zip" "./annual/Form 2 - 352 - Employee Pensions And Benefits (Account 926).zip"
cp "./compiled/Form 2 - 354 - Distribution of Salaries and Wages.zip" "./annual/Form 2 - 354 - Distribution of Salaries and Wages.zip"
cp "./compiled/Form 2 - 357 - Charges for Outside Professional and Other Consultative Services.zip" "./annual/Form 2 - 357 - Charges for Outside Professional and Other Consultative Services.zip"
cp "./compiled/Form 2 - 358 - Transactions With Associated (Affiliated) Companies.zip" "./annual/Form 2 - 358 - Transactions With Associated (Affiliated) Companies.zip"
cp "./compiled/Form 2 - 508 - Compressor Stations.zip" "./annual/Form 2 - 508 - Compressor Stations.zip"
cp "./compiled/Form 2 - 512 - Gas Storage Projects.zip" "./annual/Form 2 - 512 - Gas Storage Projects.zip"
cp "./compiled/Form 2 - 513 - Gas Storage Projects.zip" "./annual/Form 2 - 513 - Gas Storage Projects.zip"
cp "./compiled/Form 2 - 514 - Transmission Lines.zip" "./annual/Form 2 - 514 - Transmission Lines.zip"
cp "./compiled/Form 2 - 518 - Transmission System Peak Deliveries.zip" "./annual/Form 2 - 518 - Transmission System Peak Deliveries.zip"
cp "./compiled/Form 2 - 519 - Auxiliary Peaking Facilities.zip" "./annual/Form 2 - 519 - Auxiliary Peaking Facilities.zip"
cp "./compiled/Form 2 - 520 - Gas Account - Natural Gas.zip" "./annual/Form 2 - 520 - Gas Account - Natural Gas.zip"
cp "./compiled/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M1.zip" "./annual/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M1.zip"
cp "./compiled/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M2.zip" "./annual/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M2.zip"
cp "./compiled/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M3.zip" "./annual/Form 2 - 521 - Shipper Supplied Gas for the Current Quarter-M3.zip"
cp "./compiled/Form 2 - 522.1 - System Maps.zip" "./annual/Form 2 - 522.1 - System Maps.zip"