cp "./compiled/Form 1 - 000 - 1F - Cover.zip" "./form1F/Form 1 - 000 - 1F - Cover.zip"
cp "./compiled/Form 1 - 000 - 1F - Instructions.zip" "./form1F/Form 1 - 000 - 1F - Instructions.zip"
cp "./compiled/Form 1 - 000 - 1F - List of Schedules.zip" "./form1F/Form 1 - 000 - 1F - List of Schedules.zip"
cp "./compiled/Form 1 - 001 - 1F - Identification.zip" "./form1F/Form 1 - 001 - 1F - Identification.zip"
cp "./compiled/Form 1 - 002 - 1F - Annual Corporate Officer Certification.zip" "./form1F/Form 1 - 002 - 1F - Annual Corporate Officer Certification.zip"
cp "./compiled/Form 1 - 003 - 1F - Comparative Balance Sheet - Assets And Other Debits.zip" "./form1F/Form 1 - 003 - 1F - Comparative Balance Sheet - Assets And Other Debits.zip"
cp "./compiled/Form 1 - 003 - 1F - Comparative Balance Sheet - Liabilities and Other Credits.zip" "./form1F/Form 1 - 003 - 1F - Comparative Balance Sheet - Liabilities and Other Credits.zip"
cp "./compiled/Form 1 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip" "./form1F/Form 1 - 110 - Comparative Balance Sheet - Assets And Other Debits.zip"
cp "./compiled/Form 1 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip" "./form1F/Form 1 - 110 - Comparative Balance Sheet - Liabilities and Other Credits.zip"
cp "./compiled/Form 1 - 004 - 1F - Statement of Income.zip" "./form1F/Form 1 - 004 - 1F - Statement of Income.zip"
cp "./compiled/Form 1 - 114 - Statement of Income.zip" "./form1F/Form 1 - 114 - Statement of Income.zip"
cp "./compiled/Form 1 - 005 - 1F - Statement of Retained Earnings.zip" "./form1F/Form 1 - 005 - 1F - Statement of Retained Earnings.zip"
cp "./compiled/Form 1 - 118 - Statement of Retained Earnings.zip" "./form1F/Form 1 - 118 - Statement of Retained Earnings.zip"
cp "./compiled/Form 1 - 006 - 1F - Statement of Cash Flows.zip" "./form1F/Form 1 - 006 - 1F - Statement of Cash Flows.zip"
cp "./compiled/Form 1 - 007 - 1F - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip" "./form1F/Form 1 - 007 - 1F - Statement of Accumulated Other Comprehensive Income and Hedging Activities.zip"
cp "./compiled/Form 1 - 008 - 1F - Notes to Financials.zip" "./form1F/Form 1 - 008 - 1F - Notes to Financials.zip"
cp "./compiled/Form 1 - 009 - 1F - Allowances (Accounts 158.1 and 158.2).zip" "./form1F/Form 1 - 009 - 1F - Allowances (Accounts 158.1 and 158.2).zip"
cp "./compiled/Form 1 - 010 - 1F - Other Regulatory Assets.zip" "./form1F/Form 1 - 010 - 1F - Other Regulatory Assets.zip"
cp "./compiled/Form 1 - 011 - 1F - Data on Officers and Directors.zip" "./form1F/Form 1 - 011 - 1F - Data on Officers and Directors.zip"
cp "./compiled/Form 1 - 012 - 1F - Accumulated Provision for Depreciation and Amortization of Utility Plant.zip" "./form1F/Form 1 - 012 - 1F - Accumulated Provision for Depreciation and Amortization of Utility Plant.zip"
cp "./compiled/Form 1 - 219 - Accumulated Provision for Depreciation of Electric Utility Plant.zip" "./form1F/Form 1 - 219 - Accumulated Provision for Depreciation of Electric Utility Plant.zip"
cp "./compiled/Form 1 - 013 - 1F - Capital Stock.zip" "./form1F/Form 1 - 013 - 1F - Capital Stock.zip"
cp "./compiled/Form 1 - 014 - 1F - Long-Term Debt.zip" "./form1F/Form 1 - 014 - 1F - Long-Term Debt.zip"
cp "./compiled/Form 1 - 015 - 1F - Other Regulatory Liabilities (Account 254).zip" "./form1F/Form 1 - 015 - 1F - Other Regulatory Liabilities (Account 254).zip"
cp "./compiled/Form 1 - 016 - 1F - Electric Operating Revenues.zip" "./form1F/Form 1 - 016 - 1F - Electric Operating Revenues.zip"
cp "./compiled/Form 1 - 300 - Electric Operating Revenues.zip" "./form1F/Form 1 - 300 - Electric Operating Revenues.zip"
cp "./compiled/Form 1 - 017 - 1F - Electric Operations And Maintenance Expenses.zip" "./form1F/Form 1 - 017 - 1F - Electric Operations And Maintenance Expenses.zip"
cp "./compiled/Form 1 - 320 - Electric Operations And Maintenance Expenses.zip" "./form1F/Form 1 - 320 - Electric Operations And Maintenance Expenses.zip"
cp "./compiled/Form 1 - 018 - 1F - Sales for Resale.zip" "./form1F/Form 1 - 018 - 1F - Sales for Resale.zip"
cp "./compiled/Form 1 - 310 - Sales for Resale.zip" "./form1F/Form 1 - 310 - Sales for Resale.zip"
cp "./compiled/Form 1 - 019 - 1F - Purchased Power.zip" "./form1F/Form 1 - 019 - 1F - Purchased Power.zip"
cp "./compiled/Form 1 - 326 - Purchased Power.zip" "./form1F/Form 1 - 326 - Purchased Power.zip"
cp "./compiled/Form 1 - 020 - 1F - Utility Plant Data.zip" "./form1F/Form 1 - 020 - 1F - Utility Plant Data.zip"
cp "./compiled/Form 1 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip" "./form1F/Form 1 - 200 - Summary of Utility Plant and Accumulated Provisions for Depreciation, Amortization and Depletion.zip"
cp "./compiled/Form 1 - 204 - Electric Plant in Service.zip" "./form1F/Form 1 - 204 - Electric Plant in Service.zip"
cp "./compiled/Form 1 - 021 - 1F - Footnote Data.zip" "./form1F/Form 1 - 021 - 1F - Footnote Data.zip"
cp "./compiled/Form 1 - 022 - 1F - Purchases and Sales of Ancillary Services.zip" "./form1F/Form 1 - 022 - 1F - Purchases and Sales of Ancillary Services.zip"
cp "./compiled/Form 1 - 023 - 1F - Monthly Trans Peak Load.zip" "./form1F/Form 1 - 023 - 1F - Monthly Trans Peak Load.zip"
cp "./compiled/Form 1 - 024 - 1F - Transmission Service and Generation Interconnection Study Cost.zip" "./form1F/Form 1 - 024 - 1F - Transmission Service and Generation Interconnection Study Cost.zip"
cp "./compiled/Form 1 - 025 - 1F - Amounts Included in ISO RTO Settlement Statments.zip" "./form1F/Form 1 - 025 - 1F - Amounts Included in ISO RTO Settlement Statments.zip"
cp "./compiled/Form 1 - 419 - ENERGY STORAGE OPERATIONS (Small Plants).zip" "./form1F/Form 1 - 419 - ENERGY STORAGE OPERATIONS (Small Plants).zip"