python ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr' --xendr-render --noCertificateCheck --xendr-template-set '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/combined/RenderingTemplates_Form2.zip'  -f /Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/sampleInstances/Sample_Form_2.xbrl --xendr-inline '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/renderedInstance/Sample_Form_2.html'  --xendr-debug --xendr-show-xule-log --xule-arg current-start=2018-01-01 --xule-arg current-end=2018-12-31 --xule-arg $prior-start=2017-01-01 --xule-arg prior-end=2017-12-31 --xule-arg prior2-start=2016-01-01 --xule-arg prior2-end==2016-12-31 --xendr-default-footnote-page

python ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr' --xendr-render --noCertificateCheck --xendr-template-set '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/combined/RenderingTemplates_Form2.zip'  -f /Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/sampleInstances/Sample_Form_2.xbrl --xendr-inline '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/renderedInstance/Sample_Form_2.html'  --xendr-debug --xendr-show-xule-log --xule-arg  --xendr-default-footnote-page

python ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr' --xendr-render --noCertificateCheck --xendr-template-set '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/combined/RenderingTemplates_Form2.zip'  -f /Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/sampleInstances/Sample_Form_2.xbrl --xendr-inline '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/renderedInstance/Sample_Form_2.html'  --xendr-debug --xule-arg current-start=2018-01-01 --xule-arg current-end=2018-12-31 --xule-arg $prior-start=2017-01-01 --xule-arg prior-end=2017-12-31 --xule-arg prior2-start=2016-01-01 --xule-arg prior2-end==2016-12-31 


python ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr' --xendr-render --noCertificateCheck --xendr-template-set '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/combined/RenderingTemplates_Form2A.zip'  -f /Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/sampleInstances/Sample_Form_2A.xbrl --xendr-inline '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/renderedInstance/Sample_Form_2A.html' --xendr-debug

python ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr' --xendr-render --noCertificateCheck --xendr-template-set '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/combined/RenderingTemplates_Form2Q.zip'  -f /Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/sampleInstances/Sample_Form_3Q_Gas.xbrl --xendr-inline '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/renderedInstance/Sample_Form_2Q.html'  --xendr-debug

python ~/arelle/Arelle-master/arellecmdline.py --plugin xendr --xendr-compile --xendr-global "./source/render-constants.xule" --xendr-template "./source/Form 2 - 255.1 - Securities Issued or Assumed and Securities Refunded or Retired.html" --xendr-template-set "./compiled/Form 2 - 255.1 - Securities Issued or Assumed and Securities Refunded or Retired.zip"

python ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr' --xendr-render --noCertificateCheck --xendr-template-set '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/compiled/Form 2 - 255.1 - Securities Issued or Assumed and Securities Refunded or Retired.zip'  -f /Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/sampleInstances/Sample_Form_2.xbrl --xendr-inline '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/renderedInstance/Form 2 - 255.1 - Securities Issued or Assumed and Securities Refunded or Retired.html'  --xendr-debug --xendr-show-xule-log 

python ~/arelle/Arelle-master/arellecmdline.py --plugin xendr --xendr-compile --xendr-global "./source/render-constants.xule" --xendr-template "./source/Form 2 - 299 - Monthly Quantity _ Revenue Data by Rate Schedule.html" --xendr-template-set "./compiled/Form 2 - 299 - Monthly Quantity _ Revenue Data by Rate Schedule.zip"


python ~/arelle/Arelle-master/arellecmdline.py --plugin 'xendr' --xendr-render --noCertificateCheck --xendr-template-set '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/compiled/Form 2 - 299 - Monthly Quantity _ Revenue Data by Rate Schedule.zip'  -f /Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/sampleInstances/Sample_Form_2.xbrl --xendr-inline '/Users/campbellpryde/Documents/GitHub/ferc-xendr-rulesets/Form2/renderedInstance/Form 2 - 299 - Monthly Quantity _ Revenue Data by Rate Schedule.html'  --xendr-debug --xendr-show-xule-log 
